when there is nothing to compile

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -76,9 +76,14 @@ jobs:
           FAILING_TESTS_PATTERN: '/composites/dydx-rewards/|/composites/glv-token/|/composites/gm-token/|/core/bootstrap/|/sources/bitgo-reserves-test/|/sources/bitgo-reserves/|/sources/coinpaprika/|/sources/cryptocompare/|/sources/icap/|/sources/ipfs/|/sources/layer2-sequencer-health/|/sources/por-address-list/|/sources/s3-csv-reader/|/sources/view-function-multi-chain/|sources/view-function/|/k6/|/observation/'
         run: |
           set -x
-          # Tests that should compile:
-          yarn tsc -b --noEmit $(echo $CHANGED_PACKAGES | jq '.[].location + "/tsconfig.test.json"' -r | grep -v -E "$FAILING_TESTS_PATTERN")
-          # Tests that should not compile:
+          echo "Tests that should compile:"
+          for package in $(echo "$CHANGED_PACKAGES" | jq '.[].location + "/"' -r | grep -v -E "\\.|$FAILING_TESTS_PATTERN"); do
+            if ! yarn tsc -b --noEmit "${package}tsconfig.test.json"; then
+              echo "Compilation failed for $package."
+              exit 1
+            fi
+          done
+          echo "Tests that should not compile:"
           for package in $(echo "$CHANGED_PACKAGES" | jq '.[].location + "/"' -r | grep -E "\\.|$FAILING_TESTS_PATTERN"); do
             if yarn tsc -b --noEmit "${package}tsconfig.test.json"; then
               echo "Compilation succeeded for $package. Remove it from FAILING_TESTS_PATTERN so it doesn't break again in the future."
