Move README generation to gh workflow

diff --git a/.github/workflows/consume-changesets.yml b/.github/workflows/consume-changesets.yml
--- a/.github/workflows/consume-changesets.yml
+++ b/.github/workflows/consume-changesets.yml
@@ -3,7 +3,8 @@ name: Consume changesets
 on:
   push:
     branches:
-      - develop
+      # TODO revert back to develop before merging this
+      - feature/readme-generator-script
 
 jobs:
   consume-changesets:
@@ -16,10 +17,10 @@ jobs:
           # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
           fetch-depth: 0
 
-      - name: Setup Node.js 14.x
+      - name: Setup Node.js 17.x
         uses: actions/setup-node@v2
         with:
-          node-version: 14.x
+          node-version: 17.x
 
       - name: Install Dependencies
         run: yarn
@@ -27,8 +28,27 @@ jobs:
       - name: Create Release Pull Request
         uses: changesets/action@v1
         with:
+          # TODO remove [TEST]
           version: yarn changeset version
-          title: Consume changesets
-          commit: Consume changesets
+          title: '[TEST] Consume changesets'
+          commit: '[TEST] Consume changesets'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Generate READMEs
+        run: |
+          yarn setup
+          yarn generate:readme -a -v
+          README_GENERATOR_EXIT_CODE=$?
+
+          if [ $README_GENERATOR_EXIT_CODE -ne 0 ]; then
+              echo "README(s) could not be generated. Aborting commit."
+              exit 1
+          else
+              git add *
+              yarn lint-staged
+              git commit -m "Generate READMEs"
+              echo "README(s) generated successfully."
+          fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
